name: 🏗️ Build and Release Infodazz Face & School (from RVK/arun-dev-2)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # 1️⃣ Checkout SOURCE CODE (from RVK repo, branch arun-dev-2)
      - name: Checkout RVK Source Code
        uses: actions/checkout@v4
        with:
          repository: kittlesuriya/RVK
          ref: arun-dev-2
          token: ${{ secrets.SOURCE_REPO_TOKEN }}
          fetch-depth: 0

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Install Electron dependencies
      - name: Install Electron dependencies
        run: |
          cd electron
          npm ci

      # 4️⃣ Build React apps (SCHOOL + FACE)
      - name: Build React apps
        run: |
          cd SCHOOL/client && npm ci && npm run build
          cd ../../FACE/client && npm ci && npm run build
          cd ../../electron

      # 5️⃣ Build and Publish Infodazz SCHOOL app
      - name: 🏫 Build Infodazz School
        run: |
          echo "🚀 Building Infodazz School for ${{ matrix.os }}"
          cd electron
          npx electron-builder --config electron-builder-school.yml --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 6️⃣ Build and Publish Infodazz FACE app
      - name: 🧠 Build Infodazz Face
        run: |
          echo "🚀 Building Infodazz Face for ${{ matrix.os }}"
          cd electron
          npx electron-builder --config electron-builder-face.yml --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 7️⃣ Upload combined build artifacts (optional for debugging)
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Infodazz-${{ matrix.os }}
          path: electron/release/
